DROP TABLE USUARIOS;
DROP TABLE INVENTARIO;
DROP TABLE VENTAS;

CREATE TABLE USUARIOS 
(NOMBRE_USUARIO VARCHAR(20) UNIQUE PRIMARY KEY,
NUMERO_EMPLEADO INT UNIQUE AUTO_INCREMENT,
CONTRASENA VARCHAR(20) DEFAULT "usuario123",
USUARIO_ADMIN CHAR(1) CHECK(USUARIO_ADMIN IN("T", "F"))) AUTO_INCREMENT=10001;

CREATE TABLE INVENTARIO
(CODIGO_PRODUCTO INT UNIQUE PRIMARY KEY AUTO_INCREMENT,
NOMBRE_PRODUCTO VARCHAR(99) UNIQUE,
FAMILIA_PRODUCTO VARCHAR(20),
CANTIDAD_PRODCUTO INT CHECK(CANTIDAD_PRODCUTO>=0),
PRECIO_PRODUCTO DECIMAL(4,2),
IVA_PRODUCTO DECIMAL(3,2)) AUTO_INCREMENT=20001;

CREATE TABLE VENTAS
(CODIGO_PRODUCTO INT,
NOMBRE_PRODUCTO VARCHAR(20),
FAMILIA_PRODUCTO VARCHAR(20),
CANTIDAD_PRODUCTO_VENDIDO INT CHECK(CANTIDAD_PRODUCTO_VENDIDO>=0),
FECHA_VENTA DATE,
NUMERO_EMPLEADO INT);

INSERT INTO USUARIOS VALUES("admin", NULL,"admin", "T");
INSERT INTO USUARIOS VALUES("morenodavid", NULL, "12345", "F");
INSERT INTO USUARIOS VALUES("user1", NULL, "12345", "F");
INSERT INTO USUARIOS VALUES("user2", NULL, "12345", "F");

/*IVA Superreducido*/
INSERT INTO INVENTARIO VALUES(NULL, "Docena de Huevos", "Frescos", 20, 5.55, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Docena de Huevos XL", "Frescos", 20, 6.55, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Docena de Huevos Codorniz", "Frescos", 20, 6.55, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Leche Desnatada", "Lacteos", 50, 0.55, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Leche Semidesnatada", "Lacteos", 50, 0.65, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Leche Entera", "Lacteos", 50, 0.75, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Queso Semicurado", "Lacteos", 20, 3.97, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Queso Curado", "Lacteos", 20, 4.97, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Queso Rallado Mozzarella", "Lacteos", 20, 1.49, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Harina de trigo", "Cereales", 20, 0.54, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Harina de trigo fuerza", "Cereales", 20, 0.93, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Harina de trigo reposteria", "Cereales", 20, 0.99, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Banana 1Kg", "Frutas", 20, 0.95, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Aguacate 500g", "Frutas", 20, 1.99, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Manzana Golden 1Kg", "Frutas", 20, 1.75, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Cebolla 1Kg", "Hortalizas", 20, 1.79, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Espinaca troceada", "Hortaliza", 20, 0.99, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Zanahoria 1Kg", "Hortalizas", 20, 0.69, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Lechuga iceberg", "Verduras", 20, 0.99, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Brocoli", "Verduras", 20, 1.19, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Coliflor", "Verduras", 20, 2.53, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Patata 5Kg", "Tuberculos", 20, 4.99, 1.04);

INSERT INTO INVENTARIO VALUES(NULL, "Lentejas 1Kg", "Legumbres", 20, 1.95, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Alubia pinta 1Kg", "Legumbres", 20, 1.99, 1.04);
INSERT INTO INVENTARIO VALUES(NULL, "Garbanzos 1Kg", "Legumbres", 20, 2.59, 1.04);

/*IVA Reducido*/



